# Generated by Django 3.1.7 on 2021-03-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='pdf',
            field=models.FileField(upload_to='HomeWorks/pdfs/'),
        ),
    ]
