# Generated by Django 3.1.7 on 2021-03-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_homework_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='tozihat',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
