# Generated by Django 3.1.7 on 2021-03-06 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_videos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
