# Generated by Django 3.1.7 on 2021-03-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='Date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
